---

# tasks file for ansible-dockerized-owncloud
- hosts : kimsufi
  vars_files :
    - vars/external_vars.yml

  tasks:

  - name: "Pull the docker images"
    docker_image:
      name: "{{ item }}"
      state: present
      tag: latest
    with_items : "{{ docker_images_to_pull }}"


#  - block:
#    - name: "Check if volumes exist"
#      command: docker volume inspect owncloud_data
#      register: myvolume_exists
#      failed_when: false
#
#    - name: create myvolume
#      command: docker volume create --name owncloud_data -v /var/www/html owncloud /bin/true
#      when: myvolume_exists|failed
#    tags:
#      - volume
  
  - name: "create the data volume container in which Owncloud data will be stored"
    docker:
      name: owncloud_data
      image: busybox
      state: present
      volumes:
        - /var/www/html

  - name: "create the data volume in which the letsencrypt certificates will be stored "
    docker:
      name: letsencrypt
      image: busybox
      state: present
      volumes:
        - /etc/letsencrypt

  - name: "create the data volume in which the letscrypt backups wil be stored"
    docker:
      name: letsencrypt-backup
      image: busybox
      state: present
      volumes:
        - /var/lib/letsencrypt

  - name: "create the data volume in which we will cach Diffie-Hellmann parameters"
    docker:
      name: dhparam-cache
      image: busybox
      state: present
      volumes:
        - /cache

  - name: "launch database container"
    docker:
      name: "{{ owncloud_dbname }}"
      image: mariadb
      state: started
      env:
        MYSQL_ROOT_PASSWORD: "{{ owncloud_db_root_password }}"

  - name: "launch owncloud container"
    docker:
      name: owncloud
      image: owncloud
      state: started
      net: http_network
      links:
        - db_owncloud:mysql
      volumes_from:
        - owncloud_data
      ports:
        - 80

  - name: "launch nginx container with letsencrypt certificates"
    docker:
      name: lets-nginx
      image: smashwilson/lets-nginx
      state: restarted
      net: http_network
      env:
        EMAIL: "{{ email }}"
        DOMAIN: "{{ domain }}"
        UPSTREAM: "{{ upstream }}"
        STAGING: "{{ is_staging }}"
      ports:
        - 80:80
        - 443:443
      volumes_from:
        - letsencrypt
        - letsencrypt-backup
        - dhparam-cache
    tags: nginx